# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account following like this:
#---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm.serviceAccountName" . }}
  labels:
{{ include "helm.labels" . | indent 4 }}
{{- end -}}

---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#   name: fabric8-rbac
# subjects:
#   - kind: ServiceAccount
#     # Reference to upper's `metadata.name`
#     name: default
#     # Reference to upper's `metadata.namespace`
#     namespace: default
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
